### ISSUE TITLE
Title page for PDFs

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/books#19]
When downloading the manuals as pdf there should be a titlepage (green cover with senseBox logo)

**Comment by noerw** [comment]
see https://github.com/GitbookIO/feedback/issues/311
it seems they don't react on any bug reports lately.

maybe we find some other solution

**Comment by noerw** [comment]
it turns out, gitbook doesnt support covers at all anymore in its editor.
if we really need the pdf covers, we have to resort to building the PDFs ourselves again.

**Comment by noerw** [comment]
PDFs are now built on travis, with cover pages :100:
