### ISSUE TITLE
update landingpage

### ISSUE THREAD

**Issue by noerw** [sensebox/books#2]
it seems some resources have moved, `main.css` and jquery can't be found anymore when loading https://sensebox.de/books/
ping @FelixErdmann

**Comment by mpfeil** [comment]
@FelixErdmann just replace http with https for `jquery` and `main.css`
![https_books](https://cloud.githubusercontent.com/assets/2471172/16004931/d66b42d0-3164-11e6-830e-534cba8b7022.PNG)

please check the warnings and the referenced links and replace http with https

**Comment by felixerdy** [comment]
5bddf29209bbb610462cd6e542aa2a61201d7d0e
