### ISSUE TITLE
Broken link for MyOSD WiFi (PDF)

### ISSUE THREAD

**Issue by johnjohndoe** [sensebox/books#41]
I noticed that the [`MyOSD WiFi (PDF)` link](https://github.com/sensebox/books/commit/9697194c703e19214d8c22e4dfaec52329478b17#diff-08165483f3e8268773159d50ea898db0R13) on the [`book_home/de/aufbau/README.md` page](https://github.com/sensebox/books/blob/book_home/de/aufbau/README.md) is no longer reachable. I pointed out the link in the following screenshot.

![broken-link](https://user-images.githubusercontent.com/144518/27556507-24d1aa92-5ab6-11e7-8a90-59840df7c924.png)

/cc @tursics

**Comment by noerw** [comment]
Unfortunately, we do not have a copy of this file anymore.

@frankolivergloeckner @renzok Could you mail the MyOSD WiFi documentation to us, or add it in a pull request to [this folder](https://github.com/sensebox/books/tree/book_home/de/aufbau)?

**edit**: we found the document [here](http://www.my-osd.org/assets/images/Aufbau_der_MyOSD_senseBox_home_Wlan_final.pdf) and are [selfhosting](https://github.com/sensebox/resources/blob/master/guides/MyOSD_senseBox_home_Wlan.pdf) this now.

**Comment by johnjohndoe** [comment]
👍
