### ISSUE TITLE
[tawk]: BMP280 Pin SDO

### ISSUE THREAD

**Issue by mpfeil** [sensebox/books#8]
Ticket ist über tawk.to angelegt worden:

> Hi liebes SenseBox-Team, 
> 
> in der Dokumentation ist bei 4.3.4 beim Luftdruck-Sensor BMP280 ggf. zu erwähnen, dass Pin SDO auf Masse gelegt werden muss. Die Adresse über den I2C-Bus ist sonst nicht korrekt.

**Comment by noerw** [comment]
Eine den Aufbau vereinfachende Lösung wäre, unsere Version der [`BMP280.h`](https://github.com/sensebox/resources/blob/master/libraries/BMP280/BMP280.h#L109-L111) anzupassen, sodass die Adresse `0x77` verwendet wird.

Ich pushe das erstmal nicht, weil nicht klar ist wie sich das mit der senseBox:home verhält, deren Sensor keinen SDO breakoutpin hat

**Comment by noerw** [comment]
Der BMP280 in der senseBox:home nutzt die Adresse `0x76`, daher ist eine Änderung der BMP280.h ausgeschlossen.
Die Station wurde stattdessen entsprechend angepasst
